### ISSUE TITLE
[OpenBMC] Support rspconfig to set IP/NETMASK/GATEWAY using REST Interface

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3339]
Based on openbmc issue: https://github.com/openbmc/openbmc/issues/1831

Edited here by @whowutwut

---------------------------

My UT code is on `stratton01` at `/root/c910env/notes/openbmc/UT/Network/frame6u05` 

Run the following: 

```
./login.sh
./list.sh 
```

For example, we have this setting: 
```
    "/xyz/openbmc_project/network/eth0/ipv4/e2833425": {
      "Address": "10.6.5.254",
      "Gateway": "10.0.0.101",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 8,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }
```

Then the process is first we have to create a new IP object to change it...  Change the IP to 10.6.5.253

```
[root@stratton01 frame6u05]# ./set_ip.sh
You must provide the TARGET_BMC_IP address as the first argument
Usage: ./set_ip.sh <TARGET BMC IP>  <CURRENT BMC IP>


[root@stratton01 frame6u05]# ./set_ip.sh 10.6.5.253 10.6.5.254
Setting to 10.6.5.253 (8) Gateway: 10.0.0.101
NEW_VLAN=
++ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X POST -d '{"data": ["xyz.openbmc_project.Network.IP.Protocol.IPv4", "10.6.5.253", 8, "10.0.0.101"] }' https://10.6.5.254//xyz/openbmc_project/network/eth0/action/IP
curl: (52) Empty reply from server
++ cat env.config.TEMPLATE
++ sed s/__REPLACE_IP_ADDRESS__/10.6.5.253/g

```

It takes 5-10 seconds to bring up the 2nd one..  Then login and list again

```
./login.sh
./list.sh
```

And we see 2 interfaces..
```
    "/xyz/openbmc_project/network/eth0/ipv4/bb12073e": {
      "Address": "10.6.5.253",
      "Gateway": "10.0.0.101",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 8,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    },
    "/xyz/openbmc_project/network/eth0/ipv4/e2833425": {
      "Address": "10.6.5.254",
      "Gateway": "10.0.0.101",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 8,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    },
```

Now 2 inet devices are running: 
```
root@witherspoon:~# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 70:e2:84:14:28:0d brd ff:ff:ff:ff:ff:ff
    inet 10.6.5.253/8 brd 10.255.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.6.5.254/8 brd 10.255.255.255 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::72e2:84ff:fe14:280d/64 scope link
       valid_lft forever preferred_lft forever
```

both can ping...

```
}[root@stratton01 frame6u05]# ping 10.6.5.254
PING 10.6.5.254 (10.6.5.254) 56(84) bytes of data.
64 bytes from 10.6.5.254: icmp_seq=1 ttl=64 time=0.316 ms
64 bytes from 10.6.5.254: icmp_seq=2 ttl=64 time=0.308 ms
^C
--- 10.6.5.254 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.308/0.312/0.316/0.004 ms
[root@stratton01 frame6u05]# ping 10.6.5.253
PING 10.6.5.253 (10.6.5.253) 56(84) bytes of data.
64 bytes from 10.6.5.253: icmp_seq=1 ttl=64 time=0.280 ms
64 bytes from 10.6.5.253: icmp_seq=2 ttl=64 time=0.286 ms
64 bytes from 10.6.5.253: icmp_seq=3 ttl=64 time=0.263 ms
^C
--- 10.6.5.253 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.263/0.276/0.286/0.016 ms
```

Now we have to delete the other object...

```
}[root@stratton01 frame6u05]# ./delete_ip.sh e2833425
++ curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X DELETE https://10.6.5.253//xyz/openbmc_project/network/eth0/ipv4/e2833425
curl: (52) Empty reply from server
```

Again takes a few seconds to reply... Verify on the BMC
```
root@witherspoon:~# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 70:e2:84:14:28:0d brd ff:ff:ff:ff:ff:ff
    inet 10.6.5.253/8 brd 10.255.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::72e2:84ff:fe14:280d/64 scope link
       valid_lft forever preferred_lft forever
```

Change the object:
```
[root@stratton01 frame6u05]# chdef frame6u05 bmc=10.6.5.253
1 object definitions have been created or modified.
[root@stratton01 frame6u05]# rpower frame6u05 state
frame6u05: [openbmc_debug] POST https: //10.6.5.253/login -d { "data": [ "root", "0penBmc" ] }
frame6u05: [openbmc_debug] login_response 200 OK
frame6u05: [openbmc_debug] GET https: //10.6.5.253/xyz/openbmc_project/state/enumerate
frame6u05: [openbmc_debug] rpower_status_response 200 OK
frame6u05: [openbmc_debug] State CurrentBMCState=xyz.openbmc_project.State.BMC.BMCState.Ready
frame6u05: [openbmc_debug] State RequestedBMCTransition=xyz.openbmc_project.State.BMC.Transition.None
frame6u05: [openbmc_debug] State CurrentPowerState=xyz.openbmc_project.State.Chassis.PowerState.On
frame6u05: [openbmc_debug] State RequestedPowerTransition=xyz.openbmc_project.State.Chassis.Transition.Off
frame6u05: [openbmc_debug] State CurrentHostState=xyz.openbmc_project.State.Host.HostState.Running
frame6u05: [openbmc_debug] State RequestedHostTransition=xyz.openbmc_project.State.Host.Transition.On
frame6u05: on
```
Then list again...

**Comment by xuweibj** [comment]
1. Get IP information:
```
curl -b cjar -k -H "Content-Type: application/json" -X POST -d '{"data": ["eth0"]}' https://bmc/org/openbmc/NetworkManager/Interface/action/GetAddress4
{
  "data": [
    2,
    8,
    "10.6.9.254",
    "10.0.0.101"
  ],
  "message": "200 OK",
  "status": "ok"
}
```
2. Set IP/netmask/gateway
```
curl -b cjar -k -H "Content-Type: application/json" -X POST -d '{"data": ["eth0","10.6.9.254","255.0.0.0","10.0.0.101"]}' https://10.200.9.254/org/openbmc/NetworkManager/Interface/action/SetAddress4
```
Will not response and hang.

**Question**:
How to get NIC name?

**Comment by daniceexi** [comment]
@xuweibj will you check the issue with openbmc team?

**Comment by gurevichmark** [comment]
@xuweibj Have you started any work on this issue? If not, I can take it.

**Comment by gurevichmark** [comment]
Implemented query function for the `rspconfig` command under PR #3530 
Another pull request will be added to implement attribute setting for `rspconfig` command.

**Comment by gurevichmark** [comment]
Using the latest BMC build "Version": "ibm-v1.99.8-98-g06734f31-r2-0-g752ced3

The way to set Gateway property, for example, is:
```
 curl -b cjar -k -H "Content-Type: application/json" -X PUT -d '{"data": "1.2.3.4"}' https://$BMCIP/xyz/openbmc_project/network/eth0/ipv4/26238a40/attr/Gateway
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}[root@stratton01 ob910.1730.20170728n]#
```

Enumerate now shows:
```
"/xyz/openbmc_project/network/eth0/ipv4/26238a40": {
      "Address": "10.6.5.254",
      "Gateway": "1.2.3.4",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 8,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    },
```

**Comment by whowutwut** [comment]
@gurevichmark you can create a check list and it will track some sub pull request to implement the various functions in this issue

**Comment by gurevichmark** [comment]
- [ ] Query VLAN attribute
- [ ] Set VLAN attribute
- [ ] Set IP attribute
- [ ] Set NETMASK attribute
- [ ] Set GATEWAY attribute

A separate issue #3295 is there for resetting BMC to DHCP

**Comment by zet809** [comment]
hi, @gurevichmark , I think the PR for reading OpenBMC ip/netmask/gateway had been merged, will you pls link it to this issue? Thx!

**Comment by gurevichmark** [comment]
Yes, the pull request #3530 is connected to this issue.

**Comment by zet809** [comment]
Thx, @gurevichmark

**Comment by whowutwut** [comment]
@gurevichmark the check list needs to be in the first description of the issue to show up when this issue is referenced... for example, I added that test check box...
![image](https://user-images.githubusercontent.com/10049070/29343095-ed39cc86-81fc-11e7-92c8-801b9590a25a.png)

**Comment by whowutwut** [comment]
@xwbj  @gurevich   @ertaozh I think we have to come up with an external design how this would work based on my investigation for the REST calls, which I will add into the description of this issue.  I tried to ask OpenBMC team about the details for this..   

I created this issue when trying to modify an existing attribute and it did not work quite right...: https://github.com/openbmc/openbmc/issues/2163 Seems like this is not supported   

See the following up conv in slack: 
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1502936168000170

Then Ratans response: 
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1502940414000181
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1502958913000020

Not even talking about VLAN yet... if we only support 1 active configuration on the BMC...  For example, if the user runs: 
`rspconfig <> ip=192.168.9.8`

1. Now we have to get the currently configuration
2. Save the ID
3. Change anything from the current based on what the user passed in
4. Make a rest call to create the new ipv4 object 
5. Wait for the IP address to ping?
6. Delete the old object based on the saved ID... 

Or do we say we support multiple configuration of IP address on the BMC and the user is responsible for managing it, deleting , etc...

**Comment by zet809** [comment]
For me, I prefer the 1st option: we do the clean up work automatically for user to make the using much easier.
Something not clear here:
1. Can we modify the configuration for a existing network object?
2. If yes, we can modify every single attribute for the network configuration. No new network object will be created.
3. If not, it means we shall pass in BMC ip, netmask, gateway, vlan... at the same time, right? Then, a new network object is created and take affect.

So, if 2 is right, our rspconfig can be "rspconfig <node> ip=<> | netmask=<> | gateway=<> | vlan=<>".
If 3 is right, our rspconfig shall be "rspconfig <node> ip=<> netmask=<> gateway=<> vlan=<>"

**Comment by whowutwut** [comment]
@zet809 

1. If you take a look at those slack links and the converation, it seems like NO, it does not support modifying existing network objects... 
2. No supported...  
3. No, this is not good regarding usability.  That's why I wanted to discuss the usage.   

### Phase 1 - support 1 network configuration in BMC 
If we only do phase 1, then why do we need to for the user to pass in all the attributes, if they just want to change the IP addres, but leave everything the same, wouldn't it be easier for xCAT to do the work?? Get the existing config, overlay the changes, and re-create a new IP object??
 
Does the plan above seem correct or we need another logic flow? 

1. Get current config 
2. Save the ID of the network object
3. Overlay new settings on top of the current config based on what the user passed in... 
4. Make a rest call to create the new ipv4 object
5. Wait for the new IP address to become effective... 
6. Delete the old object based on the saved ID...

### Phase 2 - support multiple network configuration in BMC (future and uncommitted) 


1.  I th

**Comment by zet809** [comment]
OK, the logic is correct I think. Thx, @whowutwut

**Comment by whowutwut** [comment]
I am asking BMC team about their thoughts on the Use case for this... seems like for the creation on the first time, it's acceptable, but for modification ,it seems we should not have to do this.. but maybe VLAN adds more complexity since the URL contains the VLAN ID...

**Comment by whowutwut** [comment]
@zet809 Can you have someone own this issue?  I don't want to drive it.  We need to get this function into xCAT but the first step is to understand how to create/modify/remove on the network objects in REST and communicate directly with Ratan.   There's lots of UT examples that I have been creating.... 

This should be an EPIC and we need to break down tasks that can show process, two main pieces of this:
* Understand Setting IP address using REST outside xCAT
* Understand Setting IP address for VLAN using REST outside xCAT

Start thinking about User Case to complete: 

1.  As a xCAT administrator, I want to add and remove VLAN attribute in the BMC 
   In the event that tagging is not quite supported, we need a command that will change the BMC IP and put it into the Tagged VLAN. 
...

**Comment by xuweibj** [comment]
I have tested the flow of setting IP address using REST. 
I will go through the status of method to set VLAN tomorrow.
I think if we are sure the flow of setting IP, I could start to design our flow in xCAT.

**Comment by whowutwut** [comment]
Confirmed that we cannot modify an existing network object, so we have to create new ones to make modifications

**Comment by zet809** [comment]
I think we shall move this task to next release.

**Comment by xuweibj** [comment]
For 1738 firmware, tested two scenarios.

Scenario 1:

Static Address VLAN 11 : Add new IP object for VLAN 11, delete old object.
```
# curl -b cjar -k -H "Content-Type: application/json" -X POST -d '{"data":["xyz.openbmc_project.Network.IP.Protocol.IPv4","172.12.253.100",16,"0.0.0.0"]}' https://172.11.139.11/yz/openbmc_project/network/eth0_11/action/IP

# curl -b cjar -k -H "Content-Type: application/json" -X DELETE https://172.11.139.11/xyz/openbmc_project/network/eth0_11/ipv4/98449b01
```
Scenario 2:

DHCP Address : Add VLAN object, add IP object for the VLAN, disable DHCP of old object.
```
# curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST -d '{"data": ["eth0",11] }' https://172.12.253.103/xyz/openbmc_project/network/action/VLAN

# curl -b cjar -k -H "Content-Type: application/json" -X POST -d '{"data":["xyz.openbmc_project.Network.IP.Protocol.IPv4","172.11.139.11",16,"0.0.0.0"]}' https://172.12.253.103/xyz/openbmc_project/network/eth0_11/action/IP

# curl -b cjar -k -H "Content-Type: application/json" -X PUT -d '{"data":0}' https://172.12.253.105/xyz/openbmc_project/network/eth0/attr/DHCPEnabled
```

**Comment by xuweibj** [comment]
Mini design: https://github.com/xcat2/xcat-core/wiki/rspconfig-network

If the original IP is DHCP, we could add new object first, and then delete the old IP object. I have tested, it works.

**Comment by whowutwut** [comment]
@xuweibj  ( @gurevichmark  FYI ) In the latest FW levels as of this comment (OpenBMC 2.0 version) , the ZeroConfigIP address has been merged into the master and now is part of the OpenBMC firmware... we need to make sure that those IP addresses do not conflict with our code.
