### ISSUE TITLE
[CORAL]Bring Up the Power9 Servers in xCAT fs3 cluster

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3471]
Trace the issue https://github.ibm.com/vhu/c910env/issues/84

- [x] U03 - mid05tor12cn02 (**P9 ITC**) #72 --> HELP! Kernel Panic when installing PEGAS
                                                                     Diskless/Diskful works, but have kernel error
- [x] U05 - mid05tor12cn04 (**P9 ITC**) #88 --> HELP! need to install OS here... 
- [x] U11 - mid05tor12cn11 (**P9 ITC**) #87  --> HELP Unable to install OS here [1728B]
- [x] U13 - Power disconnected.

**Comment by zet809** [comment]
Close this task as all the ITC node are up and running.
