### ISSUE TITLE
[CORAL]investigate and enhance hardware discovery process

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3621]
* [x] why it will costs about 20 second for the discovery request to be matched? ===> #3712
* [x] how the performance will be if there are 200-500 CN doing hardware discovery at the same time? ===> covered by https://github.com/xcat2/xcat-core/issues/3711
* [x] how long will it cost to read MAC tables of more than 32 of switches (consider the MAC table size at CORAL env) ==>#3709
* [ ]  ~~only search switches that have been configured(A little special)~~
* [x] how long to deal with 1/10/100 findme requests ===> covered by https://github.com/xcat2/xcat-core/issues/3711
* [x] test the pipeline to store findme multiple packets
* [x] send processing flag to client when xCATd receive the findme request. xcatd line 801.
* [x] the performance of nmap to scan 1000,5000,10000 dynamic IPs... ==> Will be covered by #3658 
* [x] TOR  switch based switch discovery (256 in total)
* [x] store the performance data in githbub or ... ==> @robin2008  Will be covered by #3797

**Comment by immarvin** [comment]
Some points on discovery enhancement I can see:
1.  setup a framework to measure the discovery performance in a scaling environment by simulation.
    (1) Docker containers?
    (2) write customized tool to simulate the requests from different IPs and MACs
2. refine the E2E DOC to see whether it is possible to resize the IP range in each discovery phase according to the number of objects to be discovered.
3.  is it possible to make the switch based node discovery process on MN parallel? currently, it is in serial.
4. refine the code structure, remove unnecessary sleep and eliminate inefficient loops

**Comment by immarvin** [comment]
on subtask: send processing flag to client when xCATd receive the findme request in xcatd 
PR created : https://github.com/xcat2/xcat-core/pull/3678

on subtask :  test the pipeline to store findme multiple packets

The test result:
The store_fd hang after 820Bytes*100 packets was pushed in.
the environment: 
````
[root@c910f03c05k21 xcat-core]# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

[root@c910f03c05k21 xcat-core]# uname -r
3.10.0-512.el7.ppc64le

[root@c910f03c05k21 xcat-core]# cat /proc/sys/fs/pipe-max-size
1048576
````

**Comment by zet809** [comment]
This is an EPIC and need to be finished in 2.13.7, so remove the sprint label and add label to the subtasks.
