### ISSUE TITLE
license and configuration management on cumulus switch

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#4025]
according to @mattaezell in PR https://github.com/xcat2/xcat-core/pull/4005

Hi @immarvin. According to https://support.cumulusnetworks.com/hc/en-us/articles/216422657-Perpetual-Licenses-General-Questions-Current-Licensing-Model-#are_cumulus_linux_licenses_tied_to_specific_hardware you just have to make sure you don't install licenses on more switches than you paid for. If you would like, I could implement logic to allow it to try to download a hostname-specific file first.

 need to design and implement a procedure to manage the license and configuration files
* [x] design -- included in #3821 
* [ ] implementation
 
* license management             
   * [x] check whether the prokey fields  is defined as node attribute(0pts)
   * [ ] implementation of individual mode(1pts)
   * [ ] design and implementation of pool mode(2pts)
   * [ ] design and implementation the user interface to add/revoke license(1pts)

* configuration management 
   * [ ] syncfiles support on cumulus switch(0.5 pts)
   * [ ] synfiles support for node and group(0.5 pts)
   * [ ] the node-provision-like mypostscript mechanism of cumulus switch(0.5pts)
   * [ ] the default synclists including the configuration files and commands to apply them(0.5 pts)
   * [ ] snap and pull the configuration files from one or more switches based on the synclist (TBD)

**Comment by immarvin** [comment]
the config files should be associated with each switch, and license files do not need to associated to each switch

**Comment by mattaezell** [comment]
It's important to support groups for config files; all of our compute rack TOR switches will have identical configs, so we don't want to have hundreds of identical files stored on the management server.

One option could be syncfiles (#2962), but syncfiles are (currently) tied to an osimage, which we don't have on cumulus switches.

**Comment by immarvin** [comment]
hi @mattaezell , can you explain a bit on the group? is it an attribute for switch objects like node group in xCAT?

**Comment by mattaezell** [comment]
@immarvin Switches are actually `node` objects with `nodetype=switch`.  As such, they can be part of groups just like regular nodes can be.

**Comment by immarvin** [comment]
I compared the tables in xCAT db and xCAT objects:
there are 72 tables in xCAT
````
auditlog
bootparams
boottarget
cfgmgt
chain
deps
discoverydata
domain
eventlog
firmware
hosts
hwinv
hypervisor
ipmi
iscsi
kit
kitcomponent
kitrepo
kvm_masterdata
kvm_nodedata
linuximage
litefile
litetree
mac
mic
monitoring
monsetting
mp
mpa
networks
nics
nimimage
nodegroup
nodehm
nodelist
nodepos
noderes
nodetype
notification
openbmc
osdistro
osdistroupdate
osimage
passwd
pdu
pduoutlet
performance
policy
postscripts
ppc
ppcdirect
ppchcp
prescripts
prodkey
rack
routes
servicenode
site
statelite
storage
switch
switches
taskstate
token
virtsd
vm
vmmaster
vpd
websrv
winimage
zone
zvm
````

while 59 of them are abstracted or referred in xCAT objects 
````
     auditlog
     bootparams
     boottarget
     cfgmgt
     chain
     domain
     eventlog
     firmware
     hosts
     hwinv
     hypervisor
     ipmi
     iscsi
     kit
     kitcomponent
     kitrepo
     linuximage
     mac
     mic
     monitoring
     mp
     mpa
     networks
     nics
     nimimage
     nodegroup
     nodehm
     nodelist
     nodepos
     noderes
     nodetype
     notification
     openbmc
     osdistro
     osdistroupdate
     osimage
     pdu
     pduoutlet
     policy
     postscripts
     ppc
     ppcdirect
     ppchcp
     prescripts
     prodkey
     rack
     routes
     servicenode
     site
     storage
     switch
     switches
     taskstate
     vm
     vpd
     websrv
     winimage
     zone
     zvm
````

the following 13 tables are not referred at all.
````
< deps
< discoverydata
< kvm_masterdata
< kvm_nodedata
< litefile
< litetree
< monsetting
< passwd
< performance
< statelite
< token
< virtsd
< vmmaster
````

**Comment by immarvin** [comment]
hi @mattaezell , a draft mini design  of  the cumulus license and switch configuration distribution is proposed on https://github.com/xcat2/xcat-core/wiki/the-mini-design-of-license-and-network-policy-distribution

Please take a look and make sure it covers your brief requirements from a admin's perspective.  Any comment or suggest is appreciated.

thanks

**Comment by immarvin** [comment]
ping @cxhong

**Comment by immarvin** [comment]
hi @mattaezell , would you please take alook path the design? so that we can start the dev work on it ASAP, thanks

**Comment by mattaezell** [comment]
Hi @immarvin.  For CORAL Summit@ORNL, we have already distributed our license keys and interface files to all of our switches using `cumulusztp` and the postscripts.  I think the design seems OK, but we don't currently plan on reprovisioning our switches.

**Comment by immarvin** [comment]
okay, get it. We will lower the priority of this task.

 thanks

**Comment by zet809** [comment]
Thx for the information, let's remove the label high and milestone just now.

**Comment by immarvin** [comment]
covered in sycfiles support for cumulus
