### ISSUE TITLE
Version control of xCAT configuration data

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#4201]
background: https://github.com/xcat2/xcat-core/issues/4041

 * [x] propose the design of version control mechanism for xCAT configuration data: https://github.com/xcat2/xcat-core/issues/4268
 * [x] summary the schema for xCAT key objects, node/group, osimage,network, site, security,etc...: https://github.com/xcat2/xcat-core/issues/4269
 * [ ] implement the prototype for node object config file export/import

**Comment by whowutwut** [comment]
@immarvin This is a great amount of work and is it possible to scope this to something smaller, get some prototype out, get some user feedback and make sure we are doing the right thing here?? 

I saw your UT example in #4559, is the purpose of this to export the node object into yaml format to be committed into source control?   If we step back here, if we have to export and then save into source control, there's many places where we would get out of sync, and it's up to the users diligence to keep pushing changes back to the source control.. or it will be out of date. 

What I'm thinking about is the Use Case where the master configuration IS in source control in some format.. instead of the xCAT database... is this possible?   This is why I wanted to start with a smaller set like osimage only... or static config... and give us a chance to figure out if it makes sense usability wise. .  Ideally the changes would be made to the source controlled files, not xCAT, and xCAT would read them in somehow automatically...  maybe the osimage would point to the yaml file and `chdef -t osimage -o <name> --refresh` would pull in the changes.  (In this mode, we don't allow users to chdef the osimage, it has to change on the source control file)  

Here's a example scenario .... 
1. User wants to create version 173 of the osimage `abc123`..  On a test system:
   * git clone repo
   * change to the osimage directory
2. Make changes to `abc123` and genimage/packimage 
3. Deploy and Test
4. Seems to be OK, let's commit it and move to test on production system...  `git add` ... `git commit...` 
5. On production system, `git pull` and refresh the osimage in xCAT and re-deploy
6. Test it out...  uh o.. found some problem with the new image... roll back image..  using source control, get the last tagged stable version and re-depoy

Just some ideas...
