### ISSUE TITLE
[FVT] new feature verification: goconserver

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4202]
what to do:

* [x] Mini test design: [Test Design of `goconserver` Support](https://github.com/xcat2/xcat-core/wiki/Test-Design-of-%60goconserver%60-Support)
* [x] verify new feature ``goconserver`` depending on design
* [ ] performance of `goconserver`, the resource usage comparison with conserver
* [ ] stability, stress test.

Reference PR is #4199 , issue #3543
