### ISSUE TITLE
[OpenBMC]rspconfig in python

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#4674]
rspconfig support
* [x] get ip, ipsrc, netmask, 'gateway','vlan','hostname', 'ntpserver' ==> #4827 
* [x] get/set 'bootmode','autoreboot','powersupplyredundancy','powerrestorepolicy' ==> #4786 
* [x] sshcfg, bmc hostname, ip=dhcp ==> #4827 
* [x] set ntpserver, admin_passwd, gard ==> #4847 
* [x] dump  ==> #4838 
* [x] set bmc ip/netmask/gateway/vlan ==> #4884

**Comment by whowutwut** [comment]
I vote this up on the backlog since we may need to run commands against the BMC at scale.

**Comment by zet809** [comment]
* [x] get ip, ipsrc, netmask, 'gateway','vlan','hostname', 'ntpserver' ==> #4827 
* [x] get/set 'bootmode','autoreboot','powersupplyredundancy','powerrestorepolicy' ==> #4786 
* [x] sshcfg, bmc hostname, ip=dhcp ==> #4827 
* [x] set ntpserver, admin_passwd, gard ==> #4847 
* [x] dump  ==> #4838 
* [ ] set bmc ip/netmask/gateway/vlan

**Comment by zet809** [comment]
Move to 2.14 since the rspconfig set ip/netmask/gateway/vlan will be merged then.

**Comment by zet809** [comment]
Let's close this EPIC since all the subitems are finished. Thx @xuweibj and @whowutwut
