### ISSUE TITLE
Enhance the performance testing framework: xcatperftest

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4753]
@robin2008  I am trying to use this /opt/xcat/bin/xcatperftest and want to request some additional things to be added. 

- [ ] Allow the ability to specify the log file to save the output, and runs will append to the end of this file 

If I run a single test, it will save here: /opt/xcat/share/xcat/tools/autotest/result/perfreport-43.log.20180129112756 

Based on time stamp, this doesn't allow me to run a series of tests in a loop and collect the data points in a single file 

- [ ] Expand the group to allow for recording of the number of nodes.  In order to test the performance as xCAT scales to a larger range, we need this "number of nodes" data point. 

If i run the following test:
```
[root@briggs01 performance]# ./run_tests.sh
==> XCAT_GROUP=p9up
looking at ./rflash/rflash.list
Start the performance testing for commands in ./rflash/rflash.list
==================================================
[Testing for command]: rflash $XCAT_GROUP -l  ...
=====> SUCCESS, rflash, 4.71, "rflash $XCAT_GROUP -l "

Done. Check the performance result in /opt/xcat/share/xcat/tools/autotest/result/perfreport-43.log.20180129112756
```

Checking in the file, 
```
[root@briggs01 performance]# cat /opt/xcat/share/xcat/tools/autotest/result/perfreport-43.log.20180129112756
#Version 2.13.10 (git commit 7fcd37ffb7cec37c021ab47d4baec151af547ac0, built Thu Jan 25 07:15:36 EST 2018)
#Total defined nodes number: 43
#Result, Command, Time(s), Full Commands
SUCCESS, rflash, 4.71, "rflash $XCAT_GROUP -l "
```

It uses my group, so now I have lost the data that I ran against, `$XCAT_GROUP` should be recorded as the expanded command, if possible . ==> `rflash p9up -l` 

- [ ] What is the purpose of the total defined number of nodes? 

`#Total defined nodes number: 43`

This does not differentiate between switches and compute nodes., we don't have 43 compute nodes in the cluster, but 43 node objects.  

- [ ] The data recorded by this perf tool does not match the `/var/log/xcat/commands.log` file... 

```
[ElapsedTime] 4.626 s
```
and it's 4.71 in the `xcatperftest` framework, this means that we cannot gather data from commands.log and also from this performance measurement tool.

**Comment by robin2008** [comment]
@whowutwut   
For first task, now we can specify the environment variable `PERF_RPT_FILE` to specify the file name,  not sure if it meet your requirement.
```
PERF_RPT_FILE=abc.rpt xcatperftest run ./hwcmd.lst
Start the performance testing for commands in ./hwcmd.lst
==================================================
[Testing for command]: rpower p9up stat ...
=====> SUCCESS, rpower, 6.24, "rpower p9up stat"
[Testing for command]: rinv p9up all ...
=====> SUCCESS, rinv, 10.57, "rinv p9up all"
[Testing for command]: rflash p9up -l ...
=====> SUCCESS, rflash, 4.35, "rflash p9up -l"

Done. Check the performance result in /opt/xcat/share/xcat/tools/autotest/result/abc.rpt
```
run it twice and check the report file:
```
#Version 2.13.10 (git commit 7fcd37ffb7cec37c021ab47d4baec151af547ac0, built Thu Jan 25 07:15:36 EST 2018)
#Total defined nodes number: 43
#Result, Command, Time(s), Full Commands
SUCCESS, rpower, 6.24, "rpower p9up stat"
SUCCESS, rinv, 10.57, "rinv p9up all"
SUCCESS, rflash, 4.35, "rflash p9up -l"
#Version 2.13.10 (git commit 7fcd37ffb7cec37c021ab47d4baec151af547ac0, built Thu Jan 25 07:15:36 EST 2018)
#Total defined nodes number: 43
#Result, Command, Time(s), Full Commands
SUCCESS, rpower, 4.70, "rpower p9up stat"
SUCCESS, rinv, 9.18, "rinv p9up all"
SUCCESS, rflash, 2.66, "rflash p9up -l"
```

**Comment by robin2008** [comment]
For second task,  it need an enhancement,  it needs use `nodels <group>|wc -l` to get the number of nodes. 

And for the total defined nodes, it just use `nodels|wc -l` to get the number,  here is for a important reference to see what's node like objects defined in DB (server, switch, pdu, ..). some commands might be impacted when larger number nodes defined in DB.

**Comment by whowutwut** [comment]
@robin2008 thanks. I am doing some work to see if I can address some of these issues. Will update soon
