### ISSUE TITLE
[fvt] verify goconserver all opening bugs

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4869]
what to do 

* [ ] verify goconserver all opening bugs against RCs

The bug list are: 
* [ ] https://github.com/xcat2/goconserver/issues/17: File output timestamps are output before their content
* [ ] https://github.com/xcat2/goconserver/issues/18: TCP output contains carriage returns at the end of message
* [ ] https://github.com/xcat2/goconserver/issues/19: LineLogger NewLineBuf timestamp format
* [ ] https://github.com/xcat2/goconserver/issues/20: RPM upgrade overwrites server.conf
* [ ] https://github.com/xcat2/goconserver/issues/24: systemd unit file issues
* [ ] #4797 : setupconserver=2 on diskless SN does not add nodes to goconserver
