### ISSUE TITLE
Hardware control commands do not work on OP940 firmware Driver

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#6424]
## Summary of changes in OP940 discovered (so far)
- [x] New REST Server affecting all `PUT` commands. (Fixed by PR #6425)
- [x] `ipmitool` does not work for tagged VLAN. (Requested it be reinstated https://w3.rchland.ibm.com/projects/bestquest/?defect=SW470291)
- [x] Removal of `SetPassword` function. (Requested it be reinstated https://w3.rchland.ibm.com/projects/bestquest/?defect=SW476968)
- [x] Typechecking on firmware activation set priority API. Instead of `-d '{"data":false}'`, now we have to use `-d '{"data":0}'` (Fixed by PR #6433)
- [x] All REST API calls are case sensitive. For `reventlog -c` need to use `DeleteAll` instead of `deleteAll` (Fixed by PR #6433)
- [x] The `rspconfig <node> powersupplyredundancy` fails. The solution implemented for issue https://github.com/xcat2/xcat-core/issues/6270 does not work because the `description` field returned does not contain the path of the failed API. (Opened #6432 to fix) (Fixed by PR #6433)
- [ ] Default password is set to expired for new system shipped with installed OP940. Can be changed with `SetPassword` function. 

After running some tests under https://github.ibm.com/xcat2/team_process/issues/188, the hardware control commands do not work on Witherspoon machines with OP940 driver.

The `GET` commands still work, but all `PUT` commands fails with `Unauthorized` message.

OP940 uses a bmcweb REST server instead of original REST server, from the phosphor-rest-server repository, used in OP930 and OP920.

There are 2 ways to interact with the new server:
1. Pass userid and password on each REST call: `<username>:<password>@<hostname>/<path>...`. Login call is not required.
2. Use a login call to get a token, then use token on each subsequent REST call and pass that token in the header.

- Choice 1 is easier to implement and requires fewer changes to xCAT code, but is slower because a session is created for each REST call.
- Choice 2 requires more significant changes to xCAT code, but is faster.

**Comment by gurevichmark** [comment]
Closing, the latest OP940 driver 1942A has restored the changes back to OP930 version.
Verified that xCAT 2.14.6 now works with OP940.
The default password expiration function has been moved from OP940 to OP940.01
